services:
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    expose:
      - 80
    environment:
      - DOMAIN=https://vaultwarden.example.com  # 这里记得改
      - ADMIN_TOKEN="CHANGE_ME" # 密码存好
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - ADMIN_SESSION_LIFETIME=20
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
      - SIGNUPS_ALLOWED=true            # 后面可改成 false，禁止新用户注册
    volumes:
      - "./data:/data"
    restart: always
    networks:
      - proxy
networks:
  proxy:
    external: true
    name: trim-default